apiVersion: v1
kind: Service
metadata: {name: devops-capstone, labels: {app: devops-capstone}}
spec:
  selector: {app: devops-capstone}
  ports: [{port: 80, targetPort: 8080, protocol: TCP, name: http}]
  type: ClusterIP
